--Veiwing all objects in the data base
select * from INFORMATION_SCHEMA.TABLES


--veiwing all coloms in the database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'	

-- exploring all the countries 
select distinct country from gold.dim_customers

--exploring all products
select distinct category, subcategory, product_name from gold.dim_products order by 1,2,3

--finding the dates of the first and last order 
select 
max(order_date) latest_order_date, 
min(order_date) last_order_Date,
DATEDIFF(month,min(order_date),max(order_date)) as months_of_sales
from gold.fact_sales

-- finding youngest and oldest customer
select 
max(birthdate) oldest_birthdate, 
min(birthdate) youngest_birthdate,
DATEDIFF(year, min(birthdate), GETDATE()) as oldest_age,
DATEDIFF(year, max(birthdate), GETDATE()) as youngest_age
from gold.dim_customers


select 
-- finding the total sales 
sum(sales_amount) total_sales,

--finding how many items sold
sum(quantity) items_sold,

--finding avg selling price 
avg(price) average_selling_price,

--finding total amount of orders
COUNT(order_number) as total_orders,
COUNT(distinct order_number) as total_orders -- eliminating duplicates
from gold.fact_sales

select
--finding the total amount of products
count(distinct product_key) as total_products
from gold.dim_products

select
--finding the total number of customers
count(distinct customer_key) as total_customers
from gold.dim_customers

select
--finding the total number of customers that have places an order
count(distinct customer_key) as total_customers
from gold.fact_sales

--generating a report showing all key bussness merits
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total Quantity' as measure_name, sum(quantity) as measure_value from gold.fact_sales
union all 
select 'Average Price' as measure_name, avg(price) as measure_value from gold.fact_sales
union all
select 'Total Num Orders' as measure_name, COUNT(distinct order_number) as measure_value from gold.fact_sales
union all
select 'Total Num Product' as measure_name, count(distinct product_key) as measure_value from gold.fact_sales
union all
select 'Total Num Customers' as measure_name, count(distinct customer_key) as measure_value from gold.fact_sales

--finding total customers by country 
select 
country,
count(customer_key) as Total_costumer
from gold.dim_customers
group by country
order by Total_costumer desc

--finding total customers by gender
select 
gender,
count(customer_key) as Total_costumer
from gold.dim_customers
group by gender
order by Total_costumer desc

--finding total products by category
select 
category,
count(product_id) as Total_products
from gold.dim_products
group by category
order by Total_products desc

--finding avg cost in each product category
select 
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc

--finding total revenue for each product category
select 
p.category,
sum(f.sales_amount) Total_Revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by Total_Revenue desc 

--finding the total revenue generated by each costumer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) Total_Revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by
c.customer_key,
c.first_name,
c.last_name
order by Total_Revenue desc 


--finding distribution of sold items accross countries
select
c.country,
sum(f.quantity) Total_Sold_Items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by
c.country
order by Total_Sold_items desc 

--finding the 5 best performing products 
select top 5
p.product_name,
sum(f.sales_amount) Total_Revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by Total_Revenue desc 

--finding the 5 best performing products(window_func)
select * 
from (
	select
	p.product_name,
	sum(f.sales_amount) Total_Revenue,
	ROW_NUMBER() over (order by sum(f.sales_amount) desc) as rank_products
	from gold.fact_sales f
	left join gold.dim_products p
	on p.product_key = f.product_key
	group by p.product_name)t
where rank_products <= 5


--finding the 5 worst performing products 
select top 5
p.product_name,
sum(f.sales_amount) Total_Revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by Total_Revenue asc
